name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      uses: actions/checkout@v1
    - name: Checkout the code
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: upload report to github code scanning tool
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif